[workspace]
resolver = "2"
members = [
    #"f2rs",
    #"f2rs-adapter",
    "f2rs-parser-combinator",
    #"f2rs-parse",
    #"f2rs-parse/f2rs-parse-derive",
    #"example-project",
    #"xtask",
    "f2rs-parse2", "f2rs",
]
default-members = [
    "f2rs",
    #"f2rs-parse2",
]
