[workspace]
resolver = "2"
members = [
    "f2rs",
    "f2rs-adapter",
    "f2rs-adapter-derive",
    "f2rs-parser-combinator",
    "f2rs-parse",
    "f2rs-parse/f2rs-parse-derive",
    "example-project",
    "xtask",
]
default-members = [
    "f2rs",
]