[package]
name = "f2rs-parser-combinator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
serde = { version = "1.0.198", features = ["derive"] }
